instances: C:\Users\Vasileios Nastos\Desktop\Git\DitUOITeam\Cities\datasets
results: C:\Users\Vasileios Nastos\Desktop\Git\DitUOITeam\Cities\solutions
username: vasnastos
email: nastosvasileios99@gmail.com
best_solutions: C:\Users\Vasileios Nastos\Desktop\Git\DitUOITeam\Cities\best
split_token: _
objective_position: 2
root: C:\Users\Vasileios Nastos\Desktop\Git\DitUOITeam
target: [solutions, best]